esphome:
  name: temperatures_1
  platform: ESP32
  board: wemos_d1_mini32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temperatures 1 Fallback Hotspot"
    password: "yG5SiI8CdoYv"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_api_ota_pass

ota:
  password: !secret esphome_api_ota_pass

esp32_ble_tracker:

sensor:
  # Hab. Xavi
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:89:10:A7"
    temperature:
      name: "8910A7 Temperature"
    humidity:
      name: "8910A7 Humidity"
    battery_level:
      name: "8910A7 Battery Level"
    battery_voltage:
      name: "8910A7 Battery Voltage"
  # Despacho
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:9F:B0:96"
    temperature:
      name: "9FB096 Temperature"
    humidity:
      name: "9FB096 Humidity"
    battery_level:
      name: "9FB096 Battery Level"
    battery_voltage:
      name: "9FB096 Battery Voltage"
