esphome:
  name: temperatures_1
  platform: ESP32
  board: wemos_d1_mini32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temperatures 1 Fallback Hotspot"
    password: "yG5SiI8CdoYv"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_api_ota_pass

ota:
  password: !secret esphome_api_ota_pass

esp32_ble_tracker:

sensor:
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:89:10:A7"
    bindkey: "8f95f516dbe1bcd5dc7f6ed8c3067754"
    temperature:
      name: "8910A7_Temperature"
    humidity:
      name: "8910A7_Humidity"
    battery_level:
      name: "8910A7_Battery_Level"
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:9F:B0:96"
    bindkey: "c4e1bfaa0b457f4a3ddc03fc6b0f0ecc"
    temperature:
      name: "9FB096_Temperature"
    humidity:
      name: "9FB096_Humidity"
    battery_level:
      name: "9FB096_Battery Level"
